name=JkkSchedule
version=1.0.1
author=Jaromir Kopp (JKK)
maintainer=Jaromir Kopp (JKK)
sentence=Lightweight scheduling library for ESP32 with sunrise/sunset and NVS persistence.
paragraph=Primarily designed for ESP-IDF. Arduino support is experimental and currently not tested.
category=Timing
url=https://github.com/MacWyznawca/JkkSchedule
architectures=esp32
includes=JkkSchedule.h
